# Header
#menu:
  # 主页: /
  # 所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/thiagoalvernaz"
  #weibo: "#"
  rss: "/atom.xml"
  facebook: "https://www.facebook.com/thiagoalvernaz"
  # google: "#"
  # twitter: "#"
  linkedin: "https://br.linkedin.com/in/thiagoalvernaz/"

#rss
feed:
  type: atom
  path: atom.xml
  limit: 20

# Content
excerpt_link: more
fancybox: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#avatar
avatar: "http://thiagoalvernaz.github.io/img/perfil.jpg"

#share
share: true

#basta colocar seu username do disqus, para desativar bastar comentar a linha abaixo
disqus_shortname: thiagoalvernaz

#tagcloud
tagcloud: true

#Links
#Para desaivar os friends bastar passar false
friends:
  nomadev: http://nomadev.com.br
  ericdouglas: http://ericdouglas.github.io
  tableless: http://tableless.com.br
  MinasDev: http://minasdev.org

#para desativar o aboutme bastar colocar false
aboutme: Desenvolvedor Front-End a 3 anos, inicializou em 2011 como estagiário na Nave Publicidade onde realizou trabalhos nas áreas de web design e criação de peças publicitárias para a Vivo. Atualmente tem experiência em tecnologias atuais como HTML5, AngularJs, NodeJs, Javascript, CSS3, jQuery, Bootstrap e PHP, já realizou palestras sobre HTML5 e Bootstrap.